/* Savannah Lakes Village — Master Plan hotspot data
   Coordinates are % of base-map width/height. */

window.SVL = {
  meta: {
    site: "Savannah Lakes Village",
    subtitle: "Interactive Master Plan",
    place: "Lake Thurmond · McCormick County, South Carolina",
    coords: [33.86263, -82.38636],
  },

  categories: {
    hospitality: { label: "Hospitality & F&B", color: "#E0872F" },
    events:      { label: "Events & Entertainment", color: "#B0517C" },
    residential: { label: "Residential", color: "#3E8E7E" },
    marine:      { label: "Marine & Waterfront", color: "#2F7FB0" },
    amenity:     { label: "Amenities & Commons", color: "#7A8B4A" },
  },

  venues: [
    {
      id: "marina",
      name: "The Marina",
      cat: "marine",
      x: 72.5, y: 62.5,
      entity: "Savannah Lakes Resort & Marina",
      tag: "63 covered slips → 78 in Phase 1",
      lede: "The anchor asset. A deep-water covered marina held under a new 25-year federal lease controlling roughly 30 acres and about a mile of Lake Thurmond waterfront.",
      images: ["marina-aerial", "marina-slips", "pavilion-metal", "pavilion-canvas"],
      captions: [
        "Rebuilt covered slips and floating dock system — aerial",
        "Slip fairway looking toward the ship store",
        "Dock pavilion — standing-seam metal roof option",
        "Dock pavilion — tensioned canvas shade option",
      ],
      facts: [
        ["Existing slips", "63 covered"],
        ["Phase 1 slips", "78 (+15)"],
        ["Long-term potential", "300+ slips"],
        ["Lease", "25-year USACE lease"],
        ["Waterfront controlled", "~30 acres / ~1 mile"],
        ["Scope of work", "Decking, electrical and water lines"],
      ],
      notes: [
        "Roof structures and pilings are sound; decking, electrical and water lines are being fully replaced.",
        "Slip assignment is strictly first-come, first-served per the Marina Procedures & Policy Manual — required for federal lease compliance.",
        "Held independent of the residential village's liens and debt.",
        "Future cross-river expansion: 38 acres and nearly a mile of additional Georgia shoreline.",
      ],
    },
    {
      id: "dockside",
      name: "Dockside Sport & Bistro",
      cat: "hospitality",
      x: 72, y: 80,
      entity: "Dockside Bistro, LLC",
      tag: "Over-water restaurant & bar",
      lede: "The full-service, over-water dining room and bar at the head of the marina — the anchor of the peninsula food and beverage program.",
      images: ["dockside-ext", "dockside-int", "peninsula-deck"],
      captions: [
        "Over-water dining decks at golden hour",
        "Main dining room and bar interior",
        "Upper covered deck at blue hour",
      ],
      facts: [
        ["Format", "Full-service over-water dining and bar"],
        ["Position", "Head of the marina"],
        ["Seasonality", "Year-round, extended summer service"],
        ["Venue LLC", "Dockside Bistro, LLC"],
      ],
      notes: [
        "Supported by an independent bank-grade feasibility study prepared for the venue.",
        "Operating entity on all lender cover pages: Savannah Lakes Hospitality Group, LLC.",
      ],
    },
    {
      id: "tiki",
      name: "Sunset Point Tiki Sports Bar",
      cat: "hospitality",
      x: 41, y: 74.5,
      entity: "Sunset Point Tiki Bar, LLC",
      tag: "Open-air beach bar",
      lede: "A thatched, open-air sports and beach bar on the southern point — high-margin, low-overhead, and the social center of the swimming beach.",
      images: ["tiki", "beach"],
      captions: [
        "Thatched pavilion bar with sports screens at dusk",
        "The point beach immediately below the pavilion",
      ],
      facts: [
        ["Format", "Open-air, seasonal-extended"],
        ["Setting", "Southern point, above the swimming beach"],
        ["Venue LLC", "Sunset Point Tiki Bar, LLC"],
      ],
      notes: [
        "Programmed alongside the marina ship-store bar as a single beverage operation.",
        "Own single-purpose LLC so a liquor-liability or premises claim cannot reach the other venues or the marina.",
        "Requires the SC ABL license stack — SC-domestic entity with full beneficial-owner disclosure.",
      ],
    },
    {
      id: "amphitheater",
      name: "The Amphitheater",
      cat: "events",
      x: 32, y: 50,
      entity: "Amphitheatre, LLC",
      tag: "Natural-bowl concert venue",
      lede: "A covered-stage amphitheater set into the existing graded bowl on the marina point, directly west of the docks. The ground falls away to the southwest, so the stage sits at the low end and terraced lawn seating rises northeast toward the parking pad — patrons enter at the top of the bowl and walk down.",
      images: ["amphitheater", "greens"],
      captions: [
        "Evening show with full house in the bowl",
        "The commons lawn that feeds the venue",
      ],
      facts: [
        ["Siting", "Existing graded bowl, marina point"],
        ["Bowl footprint", "~1.0 acre built, 2,500 seats"],
        ["Grade", "Falls high NE → low SW"],
        ["Walk to marina docks", "~350 ft"],
        ["Walk to welcome centre", "~400 ft"],
        ["Shows per year", "~76 (twice weekly)"],
        ["Season", "Labor Day – Memorial Day"],
        ["Capacity ramp", "2,500 → 3,750 → 5,000"],
        ["Stage", "Covered stage, tiered lawn and bleachers"],
      ],
      notes: [
        "The bowl is already cleared. The dirt finger visible on current satellite imagery enters from the northeast off the existing paved loop, narrows through a gap in the pines, then spills downhill into the bowl — that finger becomes the turfed arrival lawn.",
        "Bare graded earth shown on current imagery is planned turf, not permanent hardscape.",
        "Parking and cart access already exist on the pad northeast of the bowl; no new road is required to reach it.",
        "The peninsula holds only about 1.5 acres of parking. A full house needs roughly 6.5 acres, so event parking sits on the 75-acre band and arrives by cart trail and shuttle — the trail spine is structural, not decorative.",
        "Capacity is phased so early seasons can be delivered without the full build-out.",
        "F&B, concessions and sponsorship are programmed as separate revenue lines.",
      ],
    },
    {
      id: "wedding",
      name: "The Wedding Venues",
      cat: "events",
      x: 57, y: 19,
      entity: "Savannah Lakes Hospitality Group",
      tag: "Garden, arbor & event barn",
      lede: "A formal garden ceremony landscape with an illuminated arbor tunnel, feeding a timber-and-stone event barn — paired with the cottage inventory for full-weekend buyouts.",
      images: ["wedding-garden", "barn-interior"],
      captions: [
        "Arbor tunnel and ceremony lawn at blue hour",
        "Event barn interior set for a seated reception",
      ],
      facts: [
        ["Ceremony settings", "Garden arbor, chapel, lakefront"],
        ["Reception", "Timber & stone event barn"],
        ["Paired lodging", "175 – 200 cottages"],
        ["Parking", "Dedicated event lots, north end"],
      ],
      notes: [
        "Room-night capture from the cottage inventory is the reason this venue underwrites — the venue fee alone is not the business.",
        "Modeled jointly with the cottages in the consolidated hospitality overview.",
      ],
    },
    {
      id: "chapel",
      name: "The Chapel",
      cat: "events",
      x: 22.5, y: 28,
      entity: "Savannah Lakes Hospitality Group",
      tag: "Waterfront ceremony chapel",
      lede: "A white clapboard chapel set on the west shore under the pines — the intimate-ceremony product and the visual signature of the village approach.",
      images: ["chapel"],
      captions: ["Chapel entry with floral arch, lake beyond"],
      facts: [
        ["Setting", "West shore, lake frontage"],
        ["Use", "Intimate ceremonies, services"],
        ["Adjacent", "Dedicated chapel parking"],
      ],
      notes: [
        "Second ceremony setting alongside the north-end garden, allowing two events to run without conflict.",
      ],
    },
    {
      id: "cottages",
      name: "Lakeside Cottages",
      cat: "residential",
      x: 72, y: 34,
      entity: "Savannah Lakes Hospitality Group",
      tag: "175 – 200 keys",
      lede: "Detached cottages stepped down the east shore — the lodging inventory behind the wedding, concert and marina demand.",
      images: ["cottages", "cottages-2"],
      captions: [
        "Cottage cluster with fire pit terrace at dusk",
        "Secondary cottage grouping under the pines",
      ],
      facts: [
        ["Planned keys", "175 – 200 cottages"],
        ["Position", "East shore, walk to village center"],
        ["Demand drivers", "Weddings, concerts, marina"],
        ["Use", "Short-term rental and auxiliary"],
      ],
      notes: [
        "Land designated for short-term rental and auxiliary use is carved out of the residential program.",
        "Waterfront and over-water cottage sites are also contemplated inside the federal lease area.",
      ],
    },
    {
      id: "townhomes",
      name: "The Townhomes",
      cat: "residential",
      x: 33, y: 41,
      entity: "Savannah Lakes Development Group",
      tag: "Attached for-sale product",
      lede: "Attached three-story lakeside townhomes on the west shore — the density product within the for-sale residential program.",
      images: ["townhomes"],
      captions: ["Townhome row with lake and private dock behind"],
      facts: [
        ["Builder", "EMC Homes"],
        ["Takedown structure", "Sequential 100-lot SPVs"],
        ["Shovel-ready lots", "1,847"],
        ["Product", "Attached three-story lakeside"],
      ],
      notes: [
        "Each 100-lot tranche is spun into its own SPV with unencumbered title conveyed on payment — no cross-collateralization across the village.",
        "Savannah Lakes Development Group, LLC is the Investor Manager over the residential SPVs.",
      ],
    },
    {
      id: "village-center",
      name: "The Village Center",
      cat: "amenity",
      x: 49, y: 30,
      entity: "Peninsula Park, LLC",
      tag: "Retail & plaza core",
      lede: "The clock-tower plaza at the crossroads of the peninsula — retail bays, cafe seating and the civic heart that ties the residential and hospitality halves together.",
      images: ["village-center"],
      captions: ["Village plaza and clock tower building, late afternoon"],
      facts: [
        ["Anchor", "Clock tower building"],
        ["Program", "Retail bays, cafe, plaza"],
        ["Position", "Center of the road spine"],
      ],
      notes: [
        "Positioned so cottage and townhome residents reach it on foot, and event guests pass through it arriving from US-378.",
      ],
    },
    {
      id: "opportunity-center",
      name: "The Opportunity Center",
      cat: "amenity",
      x: 61, y: 45,
      entity: "Savannah Lakes Development Group",
      tag: "Sales & discovery center",
      lede: "The sales, discovery and design-center building — where lot buyers and cottage prospects are converted on site.",
      images: ["opportunity-center"],
      captions: ["Discovery center entry and porch"],
      facts: [
        ["Function", "Sales, discovery, design center"],
        ["Partner", "EMC Homes in-office design center"],
        ["Financing", "EMC Homes buyer program"],
      ],
      notes: [
        "EMC Homes operates an in-office design center and buyer financing program out of this building.",
      ],
    },
    {
      id: "greens",
      name: "The Greens",
      cat: "amenity",
      x: 43.5, y: 62,
      entity: "Peninsula Park, LLC",
      tag: "Central commons lawn",
      lede: "The open commons between the amphitheater and the point — overflow lawn for concerts, everyday recreation, and festival grounds.",
      images: ["greens"],
      captions: ["Commons lawn at golden hour, lake on both sides"],
      facts: [
        ["Use", "Commons, overflow, festivals"],
        ["Adjacent", "Amphitheater, beach, tiki bar"],
        ["Events hosted", "BBQ Championship, sporting clays"],
      ],
      notes: [
        "Doubles as amphitheater overflow seating and as the grounds for the BBQ Championship & Food Festival.",
      ],
    },
    {
      id: "beach",
      name: "The Beach",
      cat: "amenity",
      x: 44, y: 84,
      entity: "Peninsula Park, LLC",
      tag: "Sand swimming beach",
      lede: "An imported-sand swimming beach at the southern tip, directly below the tiki pavilion — the daytime draw that feeds the bar.",
      images: ["beach", "peninsula-deck"],
      captions: [
        "The point beach with pavilion above",
        "Peninsula deck overlooking the point",
      ],
      facts: [
        ["Position", "Southern tip of the peninsula"],
        ["Paired venue", "Sunset Point Tiki Bar"],
        ["Frontage", "Protected cove, both exposures"],
      ],
      notes: [
        "No boardwalk may connect the federally leased waterfront to private property — a standing condition of the USACE lease.",
      ],
    },
  ],

  portfolio: {
    headline: "Programme at a glance",
    ramp: [
      ["Marina slips", "63 → 78 → 300+"],
      ["Cottage keys", "175 – 200"],
      ["Amphitheater", "2,500 → 5,000 seats"],
    ],
    invest: [
      ["Waterfront", "~30 acres / ~1 mile"],
      ["Federal lease", "25-year USACE"],
      ["Residential lots", "1,847 shovel-ready"],
      ["Cross-river", "38 acres in Georgia"],
    ],
    structure: [
      "Savannah Lakes Holding Company, LLC (WY) — top holdco",
      "Savannah Lakes Hospitality Group, LLC (WY) — four venue LLCs",
      "Savannah Lakes Resort & Marina, LLC (WY) — marina and resort",
      "Savannah Lakes Development Group, LLC (WY) — residential SPVs",
    ],
  },
};
